const canvas=document.getElementById("labCanvas");const ctx=canvas.getContext("2d");const dataBox=document.getElementById("graphData");const edgeStatus=document.getElementById("edgeStatus");const weightButton=document.getElementById("weightButton");let nodes=[];let edges=[];let selected=null;let selectedEdge=null;let dragging=null;let offsetX=0;let offsetY=0;let nextId=0;const r=24;
function resizeCanvas(){const dpr=window.devicePixelRatio||1;canvas.width=1100*dpr;canvas.height=560*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}window.addEventListener("resize",resizeCanvas);
function point(e){const q=canvas.getBoundingClientRect();return{x:(e.clientX-q.left)*1100/q.width,y:(e.clientY-q.top)*560/q.height}}
function nodeAt(x,y){return nodes.find(n=>Math.hypot(n.x-x,n.y-y)<=r)}
canvas.addEventListener("mousedown",e=>{const p=point(e),n=nodeAt(p.x,p.y);if(n){dragging=n;offsetX=p.x-n.x;offsetY=p.y-n.y}else{addNode(p.x,p.y)}});
canvas.addEventListener("mousemove",e=>{if(!dragging)return;const p=point(e);dragging.x=Math.max(r,Math.min(1100-r,p.x-offsetX));dragging.y=Math.max(r,Math.min(560-r,p.y-offsetY));draw()});window.addEventListener("mouseup",()=>{dragging=null});
canvas.addEventListener("click",e=>{const p=point(e),n=nodeAt(p.x,p.y);if(!n)return;if(!selected){selected=n;selectedEdge=null;weightButton.disabled=true;edgeStatus.textContent=`${n.label} selected. Choose another node.`;draw();return}if(selected.id===n.id){selected=null;selectedEdge=null;weightButton.disabled=true;edgeStatus.textContent="Selection cleared.";draw();return}const edge=edges.find(x=>(x.a===selected.id&&x.b===n.id)||(x.a===n.id&&x.b===selected.id));if(edge){selectedEdge=edge;selected=n;weightButton.disabled=false;edgeStatus.textContent=`Edge ${edgeText(edge)} selected. Edit its weight.`}else{const w=askWeight();if(w===null){selected=null}else{edges.push({a:selected.id,b:n.id,w});edgeStatus.textContent=`Edge ${selected.label}-${n.label} created with weight ${w}.`;selected=null;selectedEdge=null;weightButton.disabled=true;updateData()}}draw()});
function askWeight(){const v=prompt("Edge weight (positive number):","1");if(v===null)return null;const w=Number(v);if(!Number.isFinite(w)||w<=0){alert("Enter a positive number.");return askWeight()}return w}
function addNode(x,y){const id=++nextId;const label=id<=26?String.fromCharCode(64+id):`N${id}`;nodes.push({id,label,x,y});updateData();draw()}
function edgeText(e){const a=nodes.find(n=>n.id===e.a),b=nodes.find(n=>n.id===e.b);return `${a.label}-${b.label}-${e.w}`}
function editSelectedEdge(){if(!selectedEdge)return;const w=askWeight();if(w===null)return;selectedEdge.w=w;edgeStatus.textContent=`Updated ${edgeText(selectedEdge)}.`;updateData();draw()}
function clearGraph(){nodes=[];edges=[];selected=null;selectedEdge=null;nextId=0;weightButton.disabled=true;edgeStatus.textContent="Select two nodes to create an edge.";updateData();draw()}
function loadDemoGraph(){clearGraph();[[180,150],[420,90],[420,260],[680,150],[880,260]].forEach(([x,y])=>addNode(x,y));[[1,2,3],[1,3,2],[2,4,4],[3,4,1],[3,5,6],[4,5,2]].forEach(([a,b,w])=>edges.push({a,b,w}));updateData();draw();edgeStatus.textContent="Demo graph loaded."}
function updateData(){dataBox.value=edges.map(edgeText).join("\n")}
function copyGraphData(){if(!dataBox.value)return;navigator.clipboard?.writeText(dataBox.value);edgeStatus.textContent="Graph data copied."}
function useInSearch(){if(!dataBox.value){alert("Create at least one edge before using the graph in Search.");return}localStorage.setItem("synapseGraphInput",dataBox.value);localStorage.setItem("synapseStartNode",nodes[0]?.label||"");localStorage.setItem("synapseGoalNode",nodes[nodes.length-1]?.label||"");window.location.href="search.html"}
function draw(){ctx.clearRect(0,0,1100,560);ctx.lineWidth=2;edges.forEach(e=>{const a=nodes.find(n=>n.id===e.a),b=nodes.find(n=>n.id===e.b);if(!a||!b)return;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;ctx.fillText(String(e.w),mx+6,my-6)});nodes.forEach(n=>{ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="white";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(n.label,n.x,n.y);ctx.fillStyle="";if(selected&&selected.id===n.id){ctx.beginPath();ctx.arc(n.x,n.y,r+6,0,Math.PI*2);ctx.stroke()}})}
loadDemoGraph();resizeCanvas();